import type { Metadata } from 'next'
import styles from "@/styles/DashboardLayout.module.scss"
import { Button, Divider, Input, User } from "@nextui-org/react";
import { getUser } from '@/lib/actions';
import { signOut } from '@/auth';
import { LogOutIcon, SearchIcon, SettingsIcon } from 'lucide-react';

import Sidebar from '@/components/dashboard/layout/Sidebar';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';

export const metadata: Metadata = {
  title: 'FAJ - Dashboard',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const user = await getUser();

    return (
        <div className={styles.dashboard_layout}>
            <div className={styles.blob}></div>
            <div className={styles.sidebar}>
                <div className={styles.head}>
                    <User 
                        className='p-[20px]'  
                        name={user.username}
                        description={user.email}
                        avatarProps={{
                            src: "https://i.pravatar.cc/150?img=12"
                        }}
                    />
                </div>
                <Divider />
                <Sidebar />
            </div>
            <div className={styles.content}>
                <div className={styles.header}>
                    <Input size='sm' className={styles.searchInput} type="text" startContent={<SearchIcon size={16} />} placeholder='Serach for anything' />
                    <div className={styles.buttons}>
                        <ThemeSwitcher />
                        <Button variant='flat' isIconOnly aria-label="Settings">
                            <SettingsIcon size={16} />
                        </Button> 
                        <form
                            action={async () => {
                                'use server';
                                await signOut();
                            }}
                        >
                            <Button variant='flat' type='submit' isIconOnly aria-label="Log out">
                                <LogOutIcon size={16} />
                            </Button> 
                        </form>
                    </div>
                </div>
                <div className={styles.inner}>
                    <div className={styles.centerInner}>
                        {children}
                    </div>
                </div>
            </div>
        </div>
    )
}
